$(document).ready(function(){

	var host = localStorage.getItem("host");

	$("#demoAccnNoButton").click(function() {
		var sampleAccessionNumber = "NC_003070.9";
		$("#accnNo").val(sampleAccessionNumber);
	});

	$("#demoFastaButton").click(function() {
		var sampleFastaData = ">SEQUENCE\nGGACAGCGGAATCCTCGACCCGGTTGAGGAATGGTCGACGAAAATCTATCGGGTTCGAGGATTCGTCGACCAGGTGTTGGAATCGTCGACCGAGTCTGAGAATTCGTAGACCAGGACGGCGGAATCCTCGACAATGACGAGGTATGGTCGAGGAAAATCTATCGGGTTCGAGGATTCGTCTACCAGGTGATGGAATCCTCGACCAGGACAAAGAATTCGTCGACCAGGGGTGGAATTGTTGTTATTCCGATCATGAGAGCGGATATCAGTACAGATCCGACGCTGGTGAAAAAGATCACGGCGATCGTGGATAGTATCAAGCCACCGAGAGTCTCGTATTCGGAGAAAGATCGGCCGATGAGGATAAGAGGTCGATCGGATGGACGGAAGAGGTAGAGGAAGAGCCATGAAGCGGCGAGGCATAGGAGGAGGATGAGCGAGAATGGGTGGGCGGGAAGAGAGAAACTGATGATCAGAGCGATGATGCAGACGTAATTCACCCTGAAATAAGAGGAGTTCTTCCAGAATCGCGTCATGGCCTCGAAGACAGAGTCAAGCTTGGTGAAAAGCAGATCGTTCGAGGAGCTCTGACCACGGCCGGCTACGAGATAGACCACCACGAACCGTCTTGGTCACACTGTTGACAAATGCATGGACGGTTGGAGGTTGTGATTCCACCACATCAGTTACAATCGGAGGCTGATCCGGACTTGGCTGTTGCGGTGGTGGAAATCGGAAGCACAGGGGGATTTGTGGACACCATTCGATTTTGTTCTTTAGGGATTTCAAGATTGGAAAATTTTAGGAGACGATTGATTTGGAAGTCGGTGAAGTTTCGGTAGTGTTATGTATTTATTTTTTTTGTCATAAGCGGTAGCGTTATGTATTTGTAAGATCACATTAAGCGTCTTTCAACTTTGATTATACGCATTGCTTCATCTGATATCTAATCCATATTTTGATCAAAGTGACATTTGATAAAATAAAATAAAACTAACCTATTAATATTATAACTGAGGTTATTTTTTTAGAAAAAAGATAGCTAGCTACACGAATTATACGAGAATACATGGTCACATGCCAAGTATATTATTGTATCCTTAACTACACGAAATTTATGTATTGCATGGCCACATATATGAACTATACTACGTCATGTGGCTAACATCATAGACATATAATTCCGGTATATCGACTGGTTGACTCTGGCTTTGACTAACATTGACCGGCGTTGACCAACAAAAAATTTCAGAAAAAAACTTTAAAATAGTTTTTAATATTAAAAAATAAGAAACTGTTTTTAGGTTTTGTATAAGAAAAAAAATTCTATTTTCAGCATAGATAGATTTGTATTTTTATCCATTAAATTTTATAATAATTAGTAAAAAGTCATTATTAAATTTTAAAATATTAAAATGGAAAAATATTATTTGAACAATTAAGTAGGAAATTGCTTAAATTTATATTGTCAATTAAAAAACCTTAATTTCTATACTATTTTTATTATTATTTTGTATTTCTCAACCACAAAAATTATTAGAAGAAAACGTAATACGTATGAATTCTATTTTTATAAAAAAATTTGCTGAAATAAAAATGTTAGATCAAACAACAAAATTTGTGCCTTTCTGGTTAATGTGGAGAATATGGAAGAGTAGGAATGATCTTGTATTCAACCGGAAAAGGACTGATTTCTATACTACAGTAGAATCCGCTCTCACTGACACGAAAGAATGGCTGGGTAATATACCAACGAAAGAAGATGATCAAGGAAATGCATTGTCGCCTACGAAGAGACACACTAAGTGGAGCCCCCCCCCCCCCCCCCCCCAAAAGTGATTGGCTAAAGTGCAATTATGATGCTTCTCACCATACGGGGAATACAATGTCTGGACTAGGGTGGCTTATCCGCAACTCTCATGGCACGGTTTTGGAATGCGGTATGGGGTAGTTTCAAGGTCGAATGACTCCAGAAGAAGTTGAATGCTCGACACTTATCTGGGCTATTCAAGCCGCTAGGGCCTATGGGTATACAAAGGTGATCTTTGAAGGTGATAACATAAATATTAATCGACTAATTAACCAGAAGTCTCCAAATCCCCGACTACAACACTATCTTGATATCATATACAGTTGGATCCCAACTTTTACATCAGTAAAGTTCACCTTCAAGCATCGGGAACAAAATGCACGTGCGGATCTTTTAGCTAAGAAAGCTATTTCAGCGGATACTCATTGGTCTCTGTTTCACTCATGTCCATATTTTCTTTATCATCTTGTAAACAACGATATCTCTTAAAGTTCTAATAAAGTTTTTAGAAGGAAAAAAAAATGTTAGATTTTTTTTCTTTTTATAAAATAAAAGGAAAAATTGCAAGTTTTTTGTTTTATTATATTTTTAATTTAGTTTTGAAATTGAGAAAAATATATTTATATTGTATATAAAATATTTTTTTATTATACAGCAGGAAAAAATAATTCTTATTTTTTAATAATAAAAATAATTTTTAAGATTTTTTTGAATTTTTTGTTGGTCAAAGCCGGAATCAACTACTCAGTTTACCGAAATTGTATGTCTATGGTGTTAACCACATAACATCGTATAGTTCATATATGTGGTCATGCAATACATCTACTTTGTGTAGCTGAAGATACAATAATATAGTTAGGCAAAGTGCATTTCACCATTACTGTTCCGGTCATAGGAAGTTTCCCTGATAGAAAAAAAAAATAACACAATGTTGCTCTTTCATAAGGAGTTGTAGACTTGACAATGTCAAATCCTTTTTTCTTTGATAACATTCATCTTCGAATTCTAAACATAATTATATCTAACGAGTAGACAAAAACTACATAACCATTGTTTCCCCTGATAAGTTGTAGCATCATATATAGCATAAATGTTATTTCTTAATGCAACTTCATCAAACCTTTAGATATGTTTACAACACAAAATAATTCAAAGTTACTTGATCAATGAGAGTAGATCATACATTTCAAATTTCAGAAATTGATGTAGCAAAATGGGCTTTAATAGATACAATCAGCAGAGGGTTAGATAACTTATAAACAAAACTTAAGAGAAGAGGTGGGGTATGATTTATCTTCAGCATGAAGGTGATTTACAAGCACCGATTATAGATAAGACTCTTTGCCGAAGTTCATGAATGACCTGAAAATTGAGCAAACCAAGAAGGCTTAATACAAAAGACCAATCTTTTTGAACCGAATAATTATAGAAAGAGGAAGTCGACGAGAACGAACGGATTTGGAAGAAGAGAGCTTAGCCCATGTTTGGATATGGGCACTGCTGGTTTTGAGGTGAGAAGAGTAGGCAGCTTCTGCGTTTATGAAGTAGACTGAGTTCTCTGCTGCCTCAGCAACCCAAATTTCGTTTGTCACATCCTTTGCTCTTTTAATTAGATTGCAAAATCCGACCTGCCAAAAATTAAGACCCATAACAAGCATATATTTTTCAAAATTTAATCTCTTGGTGCATATTCTCTCTGTGTAAAACTAGACAAAGATTAGAATTTGTACATACCACGGATCCAACCAAATTATGGCTGATGTGGGAAACAGAGCTATCATCCATGAATGAGGTGCTGAAGCTTATAGCAAGAAGACTGTTTGAGATTTCCCCTGAATGTTGTGCGGATCCATCTGTCACAAACACCCACTGCTTCTTTTGTAGAACATCCGTGTATGCATTTCCAACATATACAACGTACGCAGCGATATCAAATTCACTGAAGGACATAATTAGAGATGACAGGGTATAGATTAGCAAAGTGCGGTAAAGAGTGTTTCATAAAAAGCTTGGACTACTGAGATTAACCTTGAAAGAGGAATTTCACCAAGATTTGACAAAGAGATTGGTTTACGAGGGTTGAAAAAGGGCCTGAAAACATCATCAGGGAAATTGAACAAATTAATGAGATAGATTCCAGTGTGTCTACTAAAGAAAACCACTTACTGAAAATTTTCAGAATCTTTAGGAGACAAAGGCTGCCATCTTGAGCTTGACCCTCTCGCATGTAAGTAAAGTATTTCTGAATCTGAGTTTATTGGTACTAGCCCTTTCATCATGTATATTTTCCCCTCTGTCAGCTCGGTTCTCTGTCACAGTAGTAGACAATGATAACTGTTTTAAGAATCTACAAGAAAAAAGTTGAACAAGCTAATCGATGATGCTCTTAATGCAACAGTACAGTGATGGTAACGATTCTTTGATATGCATTTCAGTCCATTCGAGGTCCACAGCAACTCTGAAAAGCTTATATTTGGAACTCCCCGTTCCATATAAGCTCATATGGATAAGGTCCGTGTAAACTTATTAGCCATTAGAAAAATGCCTTGTTTTAAATTGTGCATGAAACATTCAGATTTAGGCATTTGAATGTACCTGTCTCTCCGTGGGATCCCAGATTGTTACAATGCCTTCTTTTGGATTGTGCTCTCCTTCATAACTTAAGCTCGTCAGGCCAACAAGCCTAATCCTCATGAACGGGGTGACGTTCCTTTCACCTAAACCAGCGTCTTCCAGAGTTTCTGCCACTGATTTTTCCTTCCGCATTTGCTGGGCTGCCTGAGGTTCAGATTGAAGCAGTTAATTACTGTAATCAATATATCAAGAAAAGGAAATTACTATTCTACCTCAAATTTTGCTTTATATGTAGTGAAAGATCTCAACTGCTCTGGGCTCATTTCTGCCATAAGAAATTCAGGTTCAGCAGCCGTCTCTAACAGCTTAAAGATCTTGGCTCCTTCTTCGCTGTCAGTGTCGTTCTGGCTGTGAACACCATTAATTCCTCTCTGGTACTCACACATAATACCCTCAACAAGAGCTGAGCGCCTACGGAAAATAGAAAGAAAAAAAAAAGGCAAGTATGAATGAGAATAAACCATGACGAACTGCAATCTTTGGCTCTTTTGTTGGGAAAACCATCCATAATCAGAAGGCCAGAAGCTTTTCTAATAAATACAAAGATTGTCTTTTCTAATAAAAAATTCGAGATTAGCACTCAACATTTAATTATATGTTAGCAAATAGTATAACATTAGCTAGCAAACTTATAAACGATAAATTTGACCAAAACAACATAAACCAAGGTCACTTTATCTACTTTTTGTTCTCTGAATTCTGAAAACGAATTTGAATATCGTATTCTAACAGTGAATATTGCATTTATACTAAAATTTACGATCATAGCCATAAATAAGTAGTTATGTATAGTCAAACTATATGTAGTTATGCAGTACTTTAAGACGTTTGAACCGCTAAGATTCCCATAATCTGCATGATAATATAATGTATGTAAACTGATACATGCACAATTGCACATGATAAATATAACTAAATTGATACATGCCGATTTGCGCATGATAATTATAATTATATGCTCTATAACATGTTAGGATTTAAAATGAAAAGAGCAAATGGTTCAAGGCTGCAACTTGGTGACGCCACCAAATTGTTGTATGTAACAAAATGTCTCTAGCTTTGATGAGTTAATCTGACACTTCTTAGAAAGAGATGCATGTGCTAAATTGATCACATCAATGTTACTAAAAATTGCTCTCTACAGTTATAAGGAAACTTGCCTCTGATTATGCAGCTGTATAATTCTACTTTCTATTCTCTCTGATCGAACTATTGACTTCTTTTCACCTAACCTGTATACATCAAGAAAATATAATGCTTTGCGAGAAGTATAAAGAAGACCAAAATGCATTAACAGGCACACATTTATATTGACCTTTCCTTGTATAGGATGGGGTATATTCGTTTGATGCCAGCTAGCGTTTTAGGCACTGGACCCCCATTGCACTTGATACAATTTAAAGCCAGAGGGACACCAATTTCTTTACCTTGAGGAAGGAAGAGATTATAAACGATCAATGGAAAGATAACAATATGAAAGCAATAAGAACTCAGATGATGTAGTGAGGCCCACAGCATAAAGCTACTTACAGAAGCCTAGTCGGTCCGCCCAGTGAGCTCTGTATGTCCCATTAATATTCAACAACAAACAGATTGTACTTGAAATCACTGCCTGAAAGTTTGGTTGAATGAAACTCTTATGAACAAACCAACCTGAGAAGATATCAGAAAATCTTATAAAATGCAAAGTCTAGGAAACCTCAAGTGGTGATGTTGGGGTAGCCCAGCCAGAAAGTCCTGCCCCGAGGATCTTCAGATAAGAGATAAGAACGTAAGCATGCTGCAAGTCAGTGATCTAACCAAAATCTGTGTTGCAAAACAAAGTATATCTTGCATGAAAATAACTTACTCGAAGCTTCTGCCCGACAAACAATTTGCCAGCATTCAGCTGCTTTGTTAGTACGACATCCAGAGCAGCATTCATCGAGTACCTGTGATTTTTTTAAAAAAAATCATATGGAAATGAGTCAAGAAAACAGGTAACAGAATAGCAGTAGCAATTTCATACCACCCATCAGTGAGTTCTACTTTCACATTGCTGCAACTATCAGAACAATGTGCTTCCTGAGAATCATTATCGGTCTTTGGATTAATAGCTGATATGCAGAGCACCATCATTGAAGAAGCTGGAGCATCACCACTCAGAATCCTCTTGATTGCAGAGCAATGACCATGATTGACCTCTCTCTCATATCTATTAAGAAAGATTAACCATGTTAGACTTTGCATGAGTTTAAGTAACGAGTTGTGTTGTGAGACTGGGAAACCTGTATTTTAGTTCCTCAAGAACATTGGTGATTGTCAGAAAGTTTCCTCTGCATTTGGCTGGGTAGTATATGTCGTAGCATGCAAGTTTCCAGACTATCCACCTATAGTGATTAGTGACCCACCTAGTGCATACGTAGTGATGGATAAGTTAATAGATATAGACATCAATACTCACTGTCTATCTAATAGAGTGACAATCACATGCAAGCTTCAAAAGAACGGTCACACACTTTTTCTGATATAATAAACAAATAACACGGTTAACATTTCAAGGGACAGAGAAAGTACTTTCTGGATGCATGTTGTAAGGAAGCACCAGACTCAGCCAACATTTGAAGAAAAGTTTCAGCTCCAACCTTGTTTGAAGAAGACTCATCACAGAATACATATTTATCTGCATTACTTGATTTGATTCTTCTGACATGGTCTGGCACATAATCCATCTAAAAACCACCTCGTAAGTGTGTTTGAGTGAATGAAGAAAAAAGCTATGTAACGCAGGAACAGTTGAAAGGGACAAAAAGAATTTACCCTGGTCGTAGCTGTTGGATGCATTCCAAAAAAGTCCTTGATATATACTCTTGGAGACTTTTCTGGATACCTTGTAGAAAGCACCTTTTTGGAAGTAAGTGTATCACACGATACAACAGACAAACCTGATAATAGACAGGACACCAAAACTATAAACCTGAGAACCAACCAATTAGATTAACATAAAAAATTCTTAAAAAAATTAATCATATATATTACCACTTGAAGCTTGCAGAGCATGTTTCTTTGAAGGAGTTTTAAAGGATGAAATCCTTGGCCTTTTGAAAGGAGAAACGGAGACTGTCTTTCCCAGCCTTTTCTTTTGGGTACTGTCTTGTTTATTGTATGCATAAGCTGTATCTCTGCGATTTGTTATATCAACAAGTGGCTGATCAGCAGGCCTTCCAGGTTGCCTACCTCTTGGAATGAAACCGTTTACCTTGGAATTATTCACTGCCATATCTGATGCCAAAGACCTGTTATTTGATAGTCCATGTGTAGCATTCAGAGCACAATCGGTCTCATCAACAGCCGCATCAAATTTCTTGATCAAATTACCCCCTGAAGCTAGGTTCTCCAAGTTGACTGAACTAAATTGCTTTGAAGATGACCAAAGAGGAGATACAAAACTATTTGGCGTATGTTTGTTGCTTGTCTTTTCTTCATGAGCAATATAACCTCTGTTGGCACTTCCATTGTTTATAGCAATATCACTTA";
		$("#sequenceTextArea").val(sampleFastaData);
	});

	$("#defaultCheck").change(function() {
		if($("#defaultCheck").prop("checked")) {
			$("#mono").val(10);
			$("#di").val(6);
			$("#tri").val(5);
			$("#tetra").val(5);
			$("#penta").val(5);
			$("#hexa").val(5);
			$("#maxDiff").val(100);
		} else {
			$("#mono").val("");
			$("#di").val("");
			$("#tri").val("");
			$("#tetra").val("");
			$("#penta").val("");
			$("#hexa").val("");
			$("#maxDiff").val("");
		}
	});

	$("#mono").on('input propertychange paste', function() {
		if($("#defaultCheck").prop("checked")) {
			$("#defaultCheck").prop("checked", false);
		}
	});

	$("#di").on('input propertychange paste', function() {
		if($("#defaultCheck").prop("checked")) {
			$("#defaultCheck").prop("checked", false);
		}
	});

	$("#tri").on('input propertychange paste', function() {
		if($("#defaultCheck").prop("checked")) {
			$("#defaultCheck").prop("checked", false);
		}
	});

	$("#tetra").on('input propertychange paste', function() {
		if($("#defaultCheck").prop("checked")) {
			$("#defaultCheck").prop("checked", false);
		}
	});

	$("#penta").on('input propertychange paste', function() {
		if($("#defaultCheck").prop("checked")) {
			$("#defaultCheck").prop("checked", false);
		}
	});

	$("#hexa").on('input propertychange paste', function() {
		if($("#defaultCheck").prop("checked")) {
			$("#defaultCheck").prop("checked", false);
		}
	});

	$("#maxDiff").on('input propertychange paste', function() {
		if($("#defaultCheck").prop("checked")) {
			$("#defaultCheck").prop("checked", false);
		}
	});

	$("#clearSeqButton").click(function() {
		$("#accnNo").val("");
		$("#fastaFile").val("");
		$("#fastaFileName").val("");
		$("#sequenceTextArea").val("");
	});

	$("#clearParamButton").click(function() {
		$("#mono").val("");
		$("#di").val("");
		$("#tri").val("");
		$("#tetra").val("");
		$("#penta").val("");
		$("#hexa").val("");
		$("#maxDiff").val("");
	});

	$("#submitButton").click(function() {
		var validFlag = false;

		// Fasta contents
		var accnNo = $("#accnNo").val();
		var fastaFile = document.getElementById("fastaFile").files[0];
		var seqText = $("#sequenceTextArea").val();

		// Params
		var mono = $("#mono").val();
		var di = $("#di").val();
		var tri = $("#tri").val();
		var tetra = $("#tetra").val();
		var penta = $("#penta").val();
		var hexa = $("#hexa").val();
		var maxDiff = $("#maxDiff").val();
		var ssrRadioValue = $("input[name='optradio']:checked").val();
		var email = $("#email").val();

		if(!(accnNo || fastaFile || seqText)) {
			$("#errorText").text("Please provide one of these: Accession Number, FASTA file OR FASTA sequence!");
			$("#errorModal").modal("show");
		} else if ((accnNo && fastaFile) || (fastaFile && seqText) || (accnNo && seqText)) {
			$("#errorText").text("You only need to provide one of these: Accession Number, FASTA file OR FASTA sequence!");
			$("#errorModal").modal("show");
		} else if (!mono) {
			$("#errorText").text("Please provide value for Mono!");
			$("#errorModal").modal("show");
		} else if (!di) {
			$("#errorText").text("Please provide value for Di!");
			$("#errorModal").modal("show");
		} else if (!tri) {
			$("#errorText").text("Please provide value for Tri!");
			$("#errorModal").modal("show");
		} else if (!tetra) {
			$("#errorText").text("Please provide value for Tetra!");
			$("#errorModal").modal("show");
		} else if (!penta) {
			$("#errorText").text("Please provide value for Penta!");
			$("#errorModal").modal("show");
		} else if (!hexa) {
			$("#errorText").text("Please provide value for Hexa!");
			$("#errorModal").modal("show");
		} else if (!maxDiff) {
			$("#errorText").text("Please provide value for Maximum difference between 2 SSRs!");
			$("#errorModal").modal("show");
		} else if(email && !validateEmail(email)) {
			$("#errorText").text("Please provide valid Email!");
			$("#errorModal").modal("show");
		} else {
			validFlag = true;
		}

		if(validFlag) {
			var ssrFormData = new FormData();
			if(accnNo) {
				ssrFormData.append("typeSeq", "accnNo");
				ssrFormData.append("sequence", accnNo);
			} else if(fastaFile) {
				// Fasta file present
				ssrFormData.append("typeSeq", "file");
				ssrFormData.append("sequence", fastaFile);
			} else {
				ssrFormData.append("typeSeq", "text");
				ssrFormData.append("sequence", seqText);
			}

			ssrFormData.append("mono", mono);
			ssrFormData.append("di", di);
			ssrFormData.append("tri", tri);
			ssrFormData.append("tetra", tetra);
			ssrFormData.append("penta", penta);
			ssrFormData.append("hexa", hexa);
			ssrFormData.append("maxDiff", maxDiff);
			ssrFormData.append("ssrRadioValue", ssrRadioValue);

			$.ajax({
				url: host + "/uploadFiles.php",
				data: ssrFormData,
				processData: false,
	  			contentType: false,
				type: "POST",
				success: function(response){
					console.log(response);
					$("#successModal").modal("show");

					// Call to get the FASTA stats
					var statsUrl = host + "/getFastaStats.php?result="+response;
					$.get(statsUrl, function(data) {
						setTimeout(function(){
							$("#fastaStats").html(data);
						}, 500);
					 	
					});

     				var runUrl = host + "/runSSR.php?result="+response+"&email="+email;
                    $.get(runUrl, function(data) {
					 	window.location.href = host + "/showResults.php?result="+response;
					});
				}
			});

		}


	});

});

function isNumber(evt) {
    evt = (evt) ? evt : window.event;
    var charCode = (evt.which) ? evt.which : evt.keyCode;
    if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        return false;
    }
    return true;
}

function validateEmail(email) {
    var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(String(email).toLowerCase());
}

